### ISSUE TITLE
Dependabot Configuration

### ISSUE THREAD

**Issue by dallinb** [cbdq-io/gitchangelog#4]
Currently we have the wrong dependabot configuration.  It is configured for a dev container, but this repo doesn't have a dev container and it should be configured to update the GitHub actions.

**Comment by dallinb** [comment]
Replace the current `.github/dependabot.yml` with:

```YAML
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
```
